# Generated by Django 3.0.8 on 2020-08-31 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='images',
            table=None,
        ),
    ]
