# Generated by Django 3.0.8 on 2020-08-31 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp1', '0002_auto_20200831_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Screenshot_of_Approval',
            new_name='image',
        ),
    ]
